version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongocontainer
    ports:  
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/var/lib/mongodb
    restart: always
    command: mongod

  zookeeper:
    image: wurstmeister/zookeeper 
    ports:
      - "2181:2181"
  
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "Test5:1:1,Test4:1:1"
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1  
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

  eureka-service:
    build: ./Quiz-app
    restart: always
    container_name: eurekaContainer
    ports:
     - 8082:9090

  central-configuration:
    build: configuration-service/.
    restart: always
    container_name: configuration-serviceContainer
    ports:
     - 8888:8888
    depends_on:
      - eureka-service

